name: LotteryApp
options:
  bundleIdPrefix: com.yourname
targets:
  LotteryApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        CFBundleIconName: "AppIcon"
    settings:
      base:
        # 自动生成必须的 Info.plist 属性
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES